### ISSUE TITLE
About page appears out of date

### ISSUE THREAD

**Issue by aaronjorbin** [tollmanz/tollmanz.com-old#1]
"I am a Web Developer at The Theme Foundry".  I believe that this is no longer accurate.

**Comment by tollmanz** [comment]
Ugh...yeah...

**Comment by tollmanz** [comment]
Updated d2eb87e. It needs a full rewrite, but it's at least accurate now.

**Comment by aaronjorbin** [comment]
:+1:

**Comment by tollmanz** [comment]
This just works apparently 🤷‍♂️
